const cfg=window.PORTFOLIO_CONFIG||{};
const ready=Boolean(cfg.supabaseUrl&&cfg.supabaseAnonKey&&window.supabase);
const db=ready?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
const $=s=>document.querySelector(s);
const loginPanel=$('#loginPanel'),adminApp=$('#adminApp'),logoutBtn=$('#logoutBtn'),loginStatus=$('#loginStatus'),saveStatus=$('#saveStatus'),list=$('#adminProjectList'),rows=$('#mediaRows'),tpl=$('#mediaRowTemplate');
let currentId=null,projects=[];

function setStatus(el,msg,bad=false){el.textContent=msg||'';el.classList.toggle('bad',bad)}
function driveId(url=''){const s=String(url).trim();for(const p of [/\/file\/d\/([a-zA-Z0-9_-]+)/,/\/d\/([a-zA-Z0-9_-]+)/,/[?&]id=([a-zA-Z0-9_-]+)/]){const m=s.match(p);if(m)return m[1]}return ''}
function values(){return {title:$('#fieldTitle').value.trim(),client:$('#fieldClient').value.trim(),year:$('#fieldYear').value.trim(),category:$('#fieldCategory').value,size:$('#fieldSize').value,display_order:Number($('#fieldOrder').value||0),tags:$('#fieldTags').value.split(',').map(x=>x.trim()).filter(Boolean),description:$('#fieldDescription').value.trim(),cover_url:$('#fieldCover').value.trim(),cover_file_id:driveId($('#fieldCover').value),featured:$('#fieldFeatured').checked,published:$('#fieldPublished').checked}}
function mediaValues(){return [...rows.querySelectorAll('.media-row')].map((r,i)=>({media_type:r.querySelector('.media-type').value,source_url:r.querySelector('.media-url').value.trim(),drive_file_id:driveId(r.querySelector('.media-url').value),poster_url:r.querySelector('.media-poster').value.trim(),poster_file_id:driveId(r.querySelector('.media-poster').value),caption:r.querySelector('.media-caption').value.trim(),display_order:i})).filter(x=>x.source_url)}
function renumber(){[...rows.children].forEach((r,i)=>r.querySelector('.drag-index').textContent=String(i+1).padStart(2,'0'))}
function addMedia(m={}){const node=tpl.content.firstElementChild.cloneNode(true);node.querySelector('.media-type').value=m.media_type||'image';node.querySelector('.media-url').value=m.source_url||'';node.querySelector('.media-poster').value=m.poster_url||'';node.querySelector('.media-caption').value=m.caption||'';node.querySelector('.remove').onclick=()=>{node.remove();renumber()};node.querySelector('.move-up').onclick=()=>{const p=node.previousElementSibling;if(p)rows.insertBefore(node,p);renumber()};node.querySelector('.move-down').onclick=()=>{const n=node.nextElementSibling;if(n)rows.insertBefore(n,node);renumber()};rows.appendChild(node);renumber()}
function clearEditor(){currentId=null;$('#editorMode').textContent='NEW PROJECT';$('#editorTitle').textContent='ADD WORK.';$('#deleteProjectBtn').hidden=true;$('#fieldTitle').value='';$('#fieldClient').value='';$('#fieldYear').value='';$('#fieldCategory').value='campaign';$('#fieldSize').value='normal';$('#fieldOrder').value=projects.length;$('#fieldTags').value='';$('#fieldDescription').value='';$('#fieldCover').value='';$('#fieldFeatured').checked=true;$('#fieldPublished').checked=true;rows.innerHTML='';addMedia();setStatus(saveStatus,'')}
function fillEditor(p){currentId=p.id;$('#editorMode').textContent='EDIT PROJECT';$('#editorTitle').textContent='UPDATE WORK.';$('#deleteProjectBtn').hidden=false;$('#fieldTitle').value=p.title||'';$('#fieldClient').value=p.client||'';$('#fieldYear').value=p.year||'';$('#fieldCategory').value=p.category||'campaign';$('#fieldSize').value=p.size||'normal';$('#fieldOrder').value=p.display_order||0;$('#fieldTags').value=(p.tags||[]).join(', ');$('#fieldDescription').value=p.description||'';$('#fieldCover').value=p.cover_url||'';$('#fieldFeatured').checked=p.featured!==false;$('#fieldPublished').checked=p.published!==false;rows.innerHTML='';(p.portfolio_media||[]).sort((a,b)=>(a.display_order||0)-(b.display_order||0)).forEach(addMedia);if(!rows.children.length)addMedia();setStatus(saveStatus,'')}
function renderList(){list.innerHTML='';if(!projects.length){list.innerHTML='<p class="sidebar-empty">No projects yet.</p>';return}projects.forEach(p=>{const b=document.createElement('button');b.type='button';b.className='project-list-item'+(p.id===currentId?' active':'');b.innerHTML=`<span>${p.published?'●':'○'}</span><div><strong>${p.title}</strong><small>${p.category.toUpperCase()} · ${p.year||'—'}</small></div>`;b.onclick=()=>{fillEditor(p);renderList()};list.appendChild(b)})}
async function loadProjects(){const {data,error}=await db.from('portfolio_projects').select('*, portfolio_media(*)').order('display_order',{ascending:true});if(error){setStatus(saveStatus,error.message,true);return}projects=data||[];renderList();if(currentId){const p=projects.find(x=>x.id===currentId);if(p)fillEditor(p)}else if(projects[0]){fillEditor(projects[0]);renderList()}else clearEditor()}
async function verifyAdmin(){const {data:{session}}=await db.auth.getSession();if(!session){loginPanel.hidden=false;adminApp.hidden=true;logoutBtn.hidden=true;return}const {data,error}=await db.rpc('is_portfolio_admin');if(error||!data){await db.auth.signOut();loginPanel.hidden=false;adminApp.hidden=true;logoutBtn.hidden=true;setStatus(loginStatus,'This account is not listed in portfolio_admin_users.',true);return}loginPanel.hidden=true;adminApp.hidden=false;logoutBtn.hidden=false;await loadProjects()}

$('#loginBtn').onclick=async()=>{if(!ready){setStatus(loginStatus,'Add your Supabase URL and anon key to config.js first.',true);return}setStatus(loginStatus,'Signing in...');const {error}=await db.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(error){setStatus(loginStatus,error.message,true);return}setStatus(loginStatus,'');verifyAdmin()};
$('#signupBtn').onclick=async()=>{if(!ready){setStatus(loginStatus,'Add your Supabase URL and anon key to config.js first.',true);return}const email=$('#loginEmail').value.trim(),password=$('#loginPassword').value;if(!email||password.length<6){setStatus(loginStatus,'Enter an email and a password with at least 6 characters.',true);return}setStatus(loginStatus,'Creating account...');const {error}=await db.auth.signUp({email,password});if(error){setStatus(loginStatus,error.message,true);return}setStatus(loginStatus,'Account created. If email confirmation is enabled, confirm it first. Also add this email to portfolio_admin_users in Supabase.')};
logoutBtn.onclick=async()=>{await db.auth.signOut();location.reload()};
$('#newProjectBtn').onclick=()=>{clearEditor();renderList()};
$('#addMediaBtn').onclick=()=>addMedia();
$('#bulkAddBtn').onclick=()=>{const type=$('#bulkType').value;$('#bulkLinks').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).forEach(url=>addMedia({media_type:type,source_url:url}));$('#bulkLinks').value=''};
$('#saveProjectBtn').onclick=async()=>{const p=values();if(!p.title){setStatus(saveStatus,'Project title is required.',true);return}setStatus(saveStatus,'Saving...');let id=currentId;if(id){const {error}=await db.from('portfolio_projects').update(p).eq('id',id);if(error){setStatus(saveStatus,error.message,true);return}}else{const {data,error}=await db.from('portfolio_projects').insert(p).select('id').single();if(error){setStatus(saveStatus,error.message,true);return}id=data.id;currentId=id}
  const {error:delErr}=await db.from('portfolio_media').delete().eq('project_id',id);if(delErr){setStatus(saveStatus,delErr.message,true);return}
  const media=mediaValues().map(x=>({...x,project_id:id}));if(media.length){const {error}=await db.from('portfolio_media').insert(media);if(error){setStatus(saveStatus,error.message,true);return}}
  setStatus(saveStatus,'Saved. Your public portfolio will update automatically.');await loadProjects()};
$('#deleteProjectBtn').onclick=async()=>{if(!currentId)return;if(!confirm('Delete this project and all of its media?'))return;const {error}=await db.from('portfolio_projects').delete().eq('id',currentId);if(error){setStatus(saveStatus,error.message,true);return}currentId=null;await loadProjects();clearEditor();renderList()};

if(!ready){setStatus(loginStatus,'Setup required: add your Supabase URL + anon key in config.js.',true)}else{db.auth.onAuthStateChange(()=>setTimeout(verifyAdmin,0));verifyAdmin()}
